### ISSUE TITLE
Subtitles extracted with incorrect file extension

### ISSUE THREAD

**Issue by arkyntech** [nRafinia/Emby.Subtitle.Subscene#6]
Plugin Version: 2.2.8
Emby Version: 4.7.8.0

It seems like subtitles are being saved with the wrong extension.  

`SubtitleManager: Saving subtitles to /config/metadata/library/fe/feda30d3026e3d4252a2740fa52c1a63/(filename).6.ar.rt`

Renaming the file and doing a quick scan does resolve the issue of subtitles not being available.

**Comment by nRafinia** [comment]
Hi
Fixed in latest version
